export const GET_DATA_SEARCH = "GET_DATA_SEARCH";
export const GET_TRA_CAU_API = "GET_TRA_CAU_API";
export const GET_TRA_TU_API = "GET_TRA_TU_API";
export const GET_PHU_DE_PHIM_API = "GET_PHU_DE_PHIM_API";
export const GET_VIDEO_API = "GET_VIDEO_API";

//devfast
export const GET_MOVIES_API_DEVFAST = "GET_MOVIES_API_DEVFAST";
export const ADD_MOVIES_API_DEVFAST = "ADD_MOVIES_API_DEVFAST";
export const DEL_MOVIES_API_DEVFAST = "DEL_MOVIES_API_DEVFAST";
export const EDIT_MOVIES_API_DEVFAST = "EDIT_MOVIES_API_DEVFAST";
export const EDIT_MOVIE = "EDIT_MOVIE";
export const GET_EDIT_MOVIE = "GET_EDIT_MOVIE";
export const SAVE_WORD = "SAVE_WORD";
export const GET_INTRO = "GET_INTRO";
export const GET_TERM = "GET_TERM";
export const GET_CONTACT = "GET_CONTACT";
export const POST_NEW_WORD_API = "POST_NEW_WORD_API";

//words
export const GET_ALL_WORDS_API_DEVFAST = "GET_ALL_WORDS_API_DEVFAST";
export const GET_WORDS_API_DEVFAST = "GET_WORDS_API_DEVFAST";
export const ADD_WORDS_API_DEVFAST = "ADD_WORDS_API_DEVFAST";
export const DEL_WORDS_API_DEVFAST = "DEL_WORDS_API_DEVFAST";
export const EDIT_WORDS_API_DEVFAST = "EDIT_WORDS_API_DEVFAST";
export const EDIT_WORD = "EDIT_WORD";
export const GET_EDIT_WORD = "GET_EDIT_WORD";

// login admin
export const ADMIN_LOGIN = "ADMIN_LOGIN";

//Term
export const GET_TERM_API_DEVFAST = "GET_TERM_API_DEVFAST";
export const GET_INTRO_API_DEVFAST = "GET_INTRO_API_DEVFAST";
export const GET_CONTACT_API_DEVFAST = "GET_CONTACT_API_DEVFAST";
export const ADD_TERM_API_DEVFAST = "ADD_TERM_API_DEVFAST";
export const ADD_INTRO_API_DEVFAST = "ADD_INTRO_API_DEVFAST";
export const ADD_CONTACT_API_DEVFAST = "ADD_CONTACT_API_DEVFAST";

//customer
export const GET_CUSTOMER_API_DEVFAST = "GET_CUSTOMER_API_DEVFAST";
export const DEL_CUSTOMER_API_DEVFAST = "DEL_CUSTOMER_API_DEVFAST";

//user

export const GET_ADMIN_API_DEVFAST = "GET_ADMIN_API_DEVFAST";
export const ADD_ADMIN_API_DEVFAST = "ADD_ADMIN_API_DEVFAST";
export const DEL_ADMIN_API_DEVFAST = "DEL_ADMIN_API_DEVFAST";
export const EDIT_ADMIN_API_DEVFAST = "EDIT_ADMIN_API_DEVFAST";
export const EDIT_ADMIN = "EDIT_ADMIN";
export const GET_EDIT_ADMIN = "GET_EDIT_ADMIN";

//words unapproved
export const GET_WORDS_UNAPPROVED_API_DEVFAST =
  "GET_WORDS_UNAPPROVED_API_DEVFAST";

export const APPROVED_WORD_API = "APPROVED_WORD_API";

export const ADD_EXCEL_API_DEVFAST = "ADD_EXCEL_API_DEVFAST";

export const GET_MAIL_API_DEVFAST = "GET_MAIL_API_DEVFAST";
export const EDIT_MAIL_API_DEVFAST = "EDIT_MAIL_API_DEVFAST";


// top trendingword

export const GET_TOP_WORD ="GET_TOP_WORD"
