export const GET_DATA_SEARCH = "GET_DATA_SEARCH";
export const GET_TRA_CAU_API = "GET_TRA_CAU_API";
export const GET_TRA_TU_API = "GET_TRA_TU_API";
export const GET_PHU_DE_PHIM_API = "GET_PHU_DE_PHIM_API";
export const GET_VIDEO_API = "GET_VIDEO_API";

//devfast
export const GET_MOVIES_API_DEVFAST = "GET_MOVIES_API_DEVFAST";
export const ADD_MOVIES_API_DEVFAST = "ADD_MOVIES_API_DEVFAST";
export const DEL_MOVIES_API_DEVFAST = "DEL_MOVIES_API_DEVFAST";
export const EDIT_MOVIES_API_DEVFAST = "EDIT_MOVIES_API_DEVFAST";
export const EDIT_MOVIE = "EDIT_MOVIE";
export const GET_EDIT_MOVIE = "GET_EDIT_MOVIE";
export const SAVE_WORD = "SAVE_WORD";
